### PR TITLE
font family change

### PR DESCRIPTION
**Pull request by iammuttaqi**
- Better font, better visibility

### CODE REVIEW

**Comment by mahmudunnabikajal** [comment]
@iammuttaqi Font looks great but your plugins are making some unnecessary changes.

**Comment by iammuttaqi** [comment]
> @iammuttaqi Font looks great but your plugins are making some unnecessary changes.

It's just IDE formatting. Nothing else has changed.

**Comment by mahmudunnabikajal** [comment]
> > @iammuttaqi Font looks great but your plugins are making some unnecessary changes.
> 
> It's just IDE formatting. Nothing else has changed.

@iammuttaqi I understand. But it will create a **conflict** with the remote main when pulling for new changes.

**Comment by iammuttaqi** [comment]
> > > @iammuttaqi Font looks great but your plugins are making some unnecessary changes.
> > 
> > 
> > It's just IDE formatting. Nothing else has changed.
> 
> @iammuttaqi I understand. But it will create a **conflict** with the remote [main branch](https://github.com/vuejs/docs/tree/main) when pull for latest code.

I will resubmit then

**Comment by mahmudunnabikajal** [comment]
ok

**Pull request closed without merging**
